# Fundamentos de Numpy

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />

> Hasta ahora sólo hemos hablado acerca de tipos (clases) de variables y funciones que vienen por defecto en Python.

> Sin embargo, una de las mejores cosas de Python (especialmente si eres o te preparas para ser un científico de datos) es la gran cantidad de librerías de alto nivel que se encuentran disponibles.

> Algunas de estas librerías se encuentran en la librería estándar, es decir, se pueden encontrar donde sea que esté Python. Otras librerías se pueden añadir fácilmente.

> La primer librería externa que cubriremos en este curso es NumPy (Numerical Python).


Referencias:
- https://www.numpy.org/
- https://towardsdatascience.com/first-step-in-data-science-with-python-numpy-5e99d6821953
___

# 0. Motivación 

¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [2]:
# Crear dos vectores
x = [4, 5, 8, -2, 3]
y = [3, 1, -7, -9, 5]

In [3]:
# Suma de vectores
x + y

[4, 5, 8, -2, 3, 3, 1, -7, -9, 5]

In [5]:
# ¿con ciclos quizá?
sum_ = [x[i] + y[i] for i in range(len(x))]
sum_

[7, 6, 1, -11, 8]

In [6]:
# Producto por escalar
3 * x 

[4, 5, 8, -2, 3, 4, 5, 8, -2, 3, 4, 5, 8, -2, 3]

In [8]:
# ¿con ciclos quizá?
prod_ = [3 * x [i] for i in range(len(x))]
prod_

[12, 15, 24, -6, 9]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [66]:
# Importar numpy
import numpy as np

In [67]:
import math

In [68]:
math.e

2.718281828459045

In [69]:
np.sin(np.pi / 2)

1.0

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [70]:
# Ayuda sobre arreglo N-dimensional
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [71]:
a = [5 , 6]
a

[5, 6]

In [72]:
b = a
b

[5, 6]

In [73]:
a[0] = 6
a , b

([6, 6], [6, 6])

In [74]:
import copy
c = [7, 8]
b = copy.copy(c)
a, b, c

([6, 6], [7, 8], [7, 8])

In [75]:
# Crear dos vectores
x = np.array([4, 5, 8, -2, 3])
y = np.array([3, 1, -7, -9, 5])
x , y

(array([ 4,  5,  8, -2,  3]), array([ 3,  1, -7, -9,  5]))

In [76]:
# Tipo
type(x)

numpy.ndarray

In [77]:
# Suma de vectores
x + y

array([  7,   6,   1, -11,   8])

In [78]:
# Producto interno
7 * x

array([ 28,  35,  56, -14,  21])

In [79]:
x.dtype

dtype('int32')

In [80]:
5**np.array([28])

array([-498063855], dtype=int32)

In [81]:
np.array([5], dtype="float64")**np.array([28], dtype="float64") # == 5**28  

array([3.7252903e+19])

In [82]:
5**28 

37252902984619140625

### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

In [83]:
np.array([6, 'hola', help]) #No está diseñada para esto

array([6, 'hola',
       Type help() for interactive help, or help(object) for help about object.],
      dtype=object)

# 1. ¿Qué podemos hacer en NumPy?

Ya vimos como crear arreglos básicos en NumPy, con el comando `np.array()`

In [84]:
x = np.array([4, 5, 8, -2, 3])
y = np.array([3, 1, -7, -9, 5])

¿Cuál es el tipo de estos arreglos?

In [85]:
type(x)

numpy.ndarray

In [86]:
x.size

5

In [87]:
x.ndim

1

También podemos crear arreglos multidimensionales:

In [88]:
# Matriz 2x2
A = np.array([[1,2,0,5,-2],
              [9,-7,5,3,0],
              [2,1,1,1,-3],
              [4,8,-3,2,1]])

In [89]:
# Tipo
type(A)

numpy.ndarray

In [90]:
# array.ndim
A.ndim

2

In [91]:
A.shape

(4, 5)

In [92]:
A.size

20

In [93]:
A.ndim

2

In [94]:
len(A)

4

## 1.1 Funciones de NumPy

Seguiremos nuestra introducción a NumPy mediante la resolución del siguiente problema:

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [95]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [96]:
# Ayuda de np.random.randint()
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [100]:
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla
np.random.seed(1001)
medidas = np.random.randint(medida_min, medida_max, size=(10,))
medidas

array([18, 14, 19,  8, 17, 13, 19,  8,  9, 18])

In [101]:
# array.reshape
medidas = medidas.reshape((2,5))

In [102]:
medidas

array([[18, 14, 19,  8, 17],
       [13, 19,  8,  9, 18]])

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [104]:
# Radios
radios = medidas[0, :]
radios

array([18, 14, 19,  8, 17])

In [108]:
radios**2

array([324, 196, 361,  64, 289], dtype=int32)

In [106]:
# Alturas
alturas = medidas [1, :]
alturas

array([13, 19,  8,  9, 18])

In [109]:
alturas**2

array([169, 361,  64,  81, 324], dtype=int32)

In [110]:
radios*alturas

array([234, 266, 152,  72, 306])

1. Con lo anterior, calculemos cada uno los volúmenes:

In [111]:
# Volúmenes de los contenedores
volumenes = (np.pi * radios**2) * alturas
volumenes

array([13232.38825692, 11699.29104197,  9072.91958357,  1809.55736847,
       16342.56498397])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

2. Ahora, el volumen total

In [112]:
# Volumen total
volumenes.sum()

52156.72123489774

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [113]:
volumenes

array([13232.38825692, 11699.29104197,  9072.91958357,  1809.55736847,
       16342.56498397])

In [115]:
# Contenedor que puede almacenar más volumen
volumenes.argmax()

4

In [116]:
# Volumen máximo
volumenes.max()

16342.564983974104

In [117]:
#También se puede
max(volumenes)

16342.564983974104

4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [118]:
# Contenedor que puede almacenar menos volumen
volumenes.argmin()

3

In [119]:
# Volumen mínimo
volumenes.min()

1809.5573684677208

5. Media, mediana y desviación estándar de los volúmenes

In [121]:
# Media, mediana y desviación estándar
volumenes.mean(), np.median(volumenes), volumenes.std()

(10431.344246979548, 11699.291041968389, 4910.735052243538)

In [122]:
# Atributos shape y dtype
volumenes.shape

(5,)

In [124]:
volumenes.dtype

dtype('float64')

In [125]:
A

array([[ 1,  2,  0,  5, -2],
       [ 9, -7,  5,  3,  0],
       [ 2,  1,  1,  1, -3],
       [ 4,  8, -3,  2,  1]])

In [132]:
o, p = A.shape
o , p

(4, 5)

In [128]:
A.size

20

In [130]:
len(A)

4

## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

In [ ]:
# Ayuda en la función np.arange()


In [ ]:
# Números del 1 al 25


In [ ]:
# Ver valores


Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [ ]:
# Ayuda en la función np.random.shuffle()


In [ ]:
# Barajar


In [ ]:
# Ver valores


Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [ ]:
# Ayuda en el método np.ndarray.reshape()


In [ ]:
# Repartir cartas


In [ ]:
# Ver valores


Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [ ]:
# Ayuda en la función np.eye()


In [ ]:
# Matriz con la diagonal principal


In [ ]:
# Ayuda en la función np.ones()


In [ ]:
# Matriz con los elementos fuera de la diagonal negativos


In [ ]:
# Matriz completa


In [ ]:
# Sumar por filas


¿Quién es el ganador?

# 2. Algo de álgebra lineal con NumPy

Bueno, ya hemos utilizado NumPy para resolver algunos problemas de juguete. A través de estos problemas, hemos introducido el tipo de objetos que podemos manipular con NumPy, además de varias funcionalidades que podemos utilizar.

Pues bien, este tipo de objetos nos sirven perfectamente para representar vectores y matrices con entradas reales o complejas... si, de las que estudiamos en algún momento en álgebra lineal.

Mejor aún, NumPy nos ofrece un módulo de álgebra lineal para efectuar las operaciones básicas que podríamos necesitar.

Consideremos la siguiente matriz:

Podemos obtener varios cálculos útiles alrededor de la matriz A:

In [ ]:
# Rango de la matriz A


In [ ]:
# Determinante de la matriz A


In [ ]:
# Inversa de la matriz A


In [ ]:
# Potencia de la matriz A
# A.dot(A).dot(A).dot(A).dot(A)


In [ ]:
# Eigenvalores y eigenvectores de la matriz A


In [ ]:
# Valores propios (eigenvalores)


In [ ]:
# Vectores propios (eigenvectores)


Por otra parte, si tenemos dos vectores:

podemos calcular su producto interno (producto punto)

De la misma manera, podemos calcular la multiplicación de la matriz A por un vector

**Recomendado el siguiente [tutorial](https://www.numpy.org/devdocs/user/quickstart.html) para que profundicen más en todo lo que pueden hacer con NumPy**

<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#808080; background:#fff;">
Created with Jupyter by Esteban Jiménez Rodríguez.
</footer>