# Fundamentos de Numpy

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />

> Hasta ahora sólo hemos hablado acerca de tipos (clases) de variables y funciones que vienen por defecto en Python.

> Sin embargo, una de las mejores cosas de Python (especialmente si eres o te preparas para ser un científico de datos) es la gran cantidad de librerías de alto nivel que se encuentran disponibles.

> Algunas de estas librerías se encuentran en la librería estándar, es decir, se pueden encontrar donde sea que esté Python. Otras librerías se pueden añadir fácilmente.

> La primer librería externa que cubriremos en este curso es NumPy (Numerical Python).


Referencias:
- https://www.numpy.org/
- https://towardsdatascience.com/first-step-in-data-science-with-python-numpy-5e99d6821953
___

# 0. Motivación 

¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [1]:
# Crear dos vectores
x = [4, 5, 8, -2, 3]
y = [3, 1, -7, -9, 5]

In [2]:
# Suma de vectores
x + y

[4, 5, 8, -2, 3, 3, 1, -7, -9, 5]

In [3]:
# ¿con ciclos quizá?
sum_ = [x[i] + y[i] for i in range(len(x))]
sum_

[7, 6, 1, -11, 8]

In [4]:
# Producto por escalar
3 * x

[4, 5, 8, -2, 3, 4, 5, 8, -2, 3, 4, 5, 8, -2, 3]

In [5]:
# ¿con ciclos quizá?
prod_ = [3 * x[i] for i in range(len(x))]
prod_

[12, 15, 24, -6, 9]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [6]:
# Importar numpy
import numpy as np

In [7]:
np.sin(np.pi / 2)

1.0

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [8]:
# Ayuda sobre arreglo N-dimensional
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [9]:
a = [5, 6]
a

[5, 6]

In [10]:
import copy

In [11]:
b = copy.copy(a)

In [12]:
b

[5, 6]

In [13]:
a[1] = 8

In [14]:
b

[5, 6]

In [15]:
# Crear dos vectores
x = np.array([4, 5, 8, -2, 3])
y = np.array([3, 1, -7, -9, 5])
x, y

(array([ 4,  5,  8, -2,  3]), array([ 3,  1, -7, -9,  5]))

In [16]:
# Tipo
type(x)

numpy.ndarray

In [17]:
# Suma de vectores
x + y

array([  7,   6,   1, -11,   8])

In [18]:
# Producto interno
7 * x

array([ 28,  35,  56, -14,  21])

In [19]:
x.dtype

dtype('int64')

In [20]:
np.array([5], dtype="float64")**np.array([28], dtype="float64")  # == 5**28

array([3.7252903e+19])

In [21]:
5**28

37252902984619140625

### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

In [22]:
np.array([6, 'hola', help])

array([6, 'hola',
       Type help() for interactive help, or help(object) for help about object.],
      dtype=object)

# 1. ¿Qué podemos hacer en NumPy?

Ya vimos como crear arreglos básicos en NumPy, con el comando `np.array()`

In [23]:
x

array([ 4,  5,  8, -2,  3])

¿Cuál es el tipo de estos arreglos?

In [24]:
type(x)

numpy.ndarray

In [25]:
len(x)

5

In [26]:
x.shape

(5,)

In [27]:
x.size

5

In [28]:
x.ndim

1

También podemos crear arreglos multidimensionales:

In [29]:
# Matriz 4x5
A = np.array([[1, 2, 0, 5, -2],
              [9, -7, 5, 3, 0],
              [2, 1, 1, 1, -3],
              [4, 8, -3, 2, 1]])

In [30]:
len([[1, 2, 0, 5, -2],
     [9, -7, 5, 3, 0],
     [2, 1, 1, 1, -3],
     [4, 8, -3, 2, 1]])

4

In [31]:
# Tipo
type(A)

numpy.ndarray

In [32]:
# Atributos
A.shape

(4, 5)

In [33]:
A.size

20

In [34]:
A.ndim

2

In [35]:
len(A)

4

## 1.1 Funciones de NumPy

Seguiremos nuestra introducción a NumPy mediante la resolución del siguiente problema:

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [36]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [37]:
# Ayuda de np.random.randint()
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

In [38]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))



In [39]:
import numpy as np

In [42]:
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla
np.random.seed(1001)
medidas = np.random.randint(medida_min, medida_max, size=(10,))

In [43]:
# Ver valores
medidas

array([18, 14, 19,  8, 17, 13, 19,  8,  9, 18])

In [44]:
help(medidas.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [45]:
# array.reshape
medidas = medidas.reshape((2, 5))

In [46]:
medidas

array([[18, 14, 19,  8, 17],
       [13, 19,  8,  9, 18]])

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [47]:
# Radios
radios = medidas[0, :]
radios

array([18, 14, 19,  8, 17])

In [50]:
medidas[:, 3:5]

array([[ 8, 17],
       [ 9, 18]])

In [51]:
medidas[:, ::2]

array([[18, 19, 17],
       [13,  8, 18]])

In [49]:
# Alturas
alturas = medidas[1, :]
alturas

array([13, 19,  8,  9, 18])

1. Con lo anterior, calculemos cada uno los volúmenes:

In [53]:
radios

array([18, 14, 19,  8, 17])

In [55]:
radios**2

array([324, 196, 361,  64, 289])

In [54]:
alturas

array([13, 19,  8,  9, 18])

In [52]:
# Volúmenes de los contenedores
volumenes = (np.pi * radios**2) * alturas
volumenes

array([13232.38825692, 11699.29104197,  9072.91958357,  1809.55736847,
       16342.56498397])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

2. Ahora, el volumen total

In [56]:
# Volumen total
volumenes.sum()

52156.72123489774

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [58]:
volumenes

array([13232.38825692, 11699.29104197,  9072.91958357,  1809.55736847,
       16342.56498397])

In [57]:
# Contenedor que puede almacenar más volumen
volumenes.argmax()

4

In [59]:
# Volumen máximo
volumenes.max()

16342.564983974104

In [60]:
# También se puede, pero no es recomendable. Ver comparación de tiempos
max(volumenes)

16342.564983974104

In [64]:
random_vector = np.random.randint(0, 1000, size=(1000,))

In [73]:
%timeit random_vector.max()

5.22 µs ± 58.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [74]:
%timeit np.max(random_vector)

7.95 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [66]:
%timeit max(random_vector)

181 µs ± 4.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [68]:
# Contenedor que puede almacenar menos volumen
volumenes.argmin()

3

In [67]:
# Volumen mínimo
volumenes.min()

1809.5573684677208

5. Media, mediana y desviación estándar de los volúmenes

In [70]:
# Media, mediana y desviación estándar
volumenes.mean(), volumenes.std()

(10431.344246979548, 4910.735052243538)

In [71]:
np.median(volumenes)

11699.291041968389

In [75]:
# Atributos shape y dtype
volumenes.shape

(5,)

In [76]:
volumenes.dtype

dtype('float64')

In [77]:
A

array([[ 1,  2,  0,  5, -2],
       [ 9, -7,  5,  3,  0],
       [ 2,  1,  1,  1, -3],
       [ 4,  8, -3,  2,  1]])

In [78]:
A.shape

(4, 5)

In [79]:
A.size

20

## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

np.arange = np.array(range)

In [83]:
# Ayuda en la función np.arange()
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [82]:
# Números del 1 al 25
cartas = np.arange(1, 26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [84]:
# Ayuda en la función np.random.shuffle()
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the ``shuffle`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random

In [85]:
# Barajar
np.random.shuffle(cartas)

In [86]:
# Ver valores
cartas

array([13, 16, 17, 12,  9, 11, 23, 14,  3,  7, 19, 25, 20, 24,  1,  8, 18,
        6, 22, 21, 15,  4,  5, 10,  2])

Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [87]:
# Repartir cartas
cartas = cartas.reshape((5, 5))

In [88]:
# Ver valores
cartas

array([[13, 16, 17, 12,  9],
       [11, 23, 14,  3,  7],
       [19, 25, 20, 24,  1],
       [ 8, 18,  6, 22, 21],
       [15,  4,  5, 10,  2]])

Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [89]:
# Ayuda en la función np.eye()
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [90]:
# Matriz con la diagonal principal
I5 = np.eye(5)

In [91]:
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
I5 * cartas

array([[13.,  0.,  0.,  0.,  0.],
       [ 0., 23.,  0.,  0.,  0.],
       [ 0.,  0., 20.,  0.,  0.],
       [ 0.,  0.,  0., 22.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [93]:
# Ayuda en la función np.ones()
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [94]:
# Matriz con los elementos fuera de la diagonal negativos
complement = np.ones((5, 5)) - I5

In [95]:
complement

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [96]:
complement * cartas

array([[ 0., 16., 17., 12.,  9.],
       [11.,  0., 14.,  3.,  7.],
       [19., 25.,  0., 24.,  1.],
       [ 8., 18.,  6.,  0., 21.],
       [15.,  4.,  5., 10.,  0.]])

In [97]:
# Matriz completa
matriz_para_suma = I5 * cartas - complement * cartas

In [98]:
matriz_para_suma

array([[ 13., -16., -17., -12.,  -9.],
       [-11.,  23., -14.,  -3.,  -7.],
       [-19., -25.,  20., -24.,  -1.],
       [ -8., -18.,  -6.,  22., -21.],
       [-15.,  -4.,  -5., -10.,   2.]])

In [104]:
# Sumar por filas
suma = matriz_para_suma.sum(axis=0)
suma

array([-40., -40., -22., -27., -36.])

¿Quién es el ganador?

In [101]:
suma.argmax()

2

# 2. Algo de álgebra lineal con NumPy

Bueno, ya hemos utilizado NumPy para resolver algunos problemas de juguete. A través de estos problemas, hemos introducido el tipo de objetos que podemos manipular con NumPy, además de varias funcionalidades que podemos utilizar.

Pues bien, este tipo de objetos nos sirven perfectamente para representar vectores y matrices con entradas reales o complejas... si, de las que estudiamos en algún momento en álgebra lineal.

Mejor aún, NumPy nos ofrece un módulo de álgebra lineal para efectuar las operaciones básicas que podríamos necesitar.

Consideremos la siguiente matriz:

In [105]:
A = np.array([[1, 0, 1],
              [-1, 2, 4],
              [2, 1, 1]])

In [106]:
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

Podemos obtener varios cálculos útiles alrededor de la matriz A:

In [107]:
# Rango de la matriz A
np.linalg.matrix_rank(A)

3

In [108]:
# Determinante de la matriz A
np.linalg.det(A)

-7.000000000000001

In [109]:
# Inversa de la matriz A
np.linalg.inv(A)

array([[ 0.28571429, -0.14285714,  0.28571429],
       [-1.28571429,  0.14285714,  0.71428571],
       [ 0.71428571,  0.14285714, -0.28571429]])

In [111]:
A.dot(np.linalg.inv(A))

array([[ 1.00000000e+00,  2.77555756e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  2.77555756e-17,  1.00000000e+00]])

In [113]:
np.linalg.inv(A).dot(A)

array([[ 1.00000000e+00,  5.55111512e-17,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [112]:
np.dot(A, np.linalg.inv(A))

array([[ 1.00000000e+00,  2.77555756e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  2.77555756e-17,  1.00000000e+00]])

In [114]:
np.dot(np.linalg.inv(A), A)

array([[ 1.00000000e+00,  5.55111512e-17,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [115]:
# Potencia de la matriz A
# A.dot(A).dot(A).dot(A).dot(A)
np.linalg.matrix_power(A, 5)

array([[ 65,  65, 119],
       [336, 379, 671],
       [173, 184, 325]])

In [116]:
A.dot(A).dot(A).dot(A).dot(A)

array([[ 65,  65, 119],
       [336, 379, 671],
       [173, 184, 325]])

In [117]:
A**5

array([[   1,    0,    1],
       [  -1,   32, 1024],
       [  32,    1,    1]])

In [118]:
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

In [120]:
# Eigenvalores y eigenvectores de la matriz A
l, v = np.linalg.eig(A)

In [121]:
l

array([-1.25341804,  1.48003063,  3.77338741])

In [122]:
v

array([[ 0.25358082,  0.47881379,  0.15600857],
       [ 0.78049461, -0.84729481,  0.8879505 ],
       [-0.5714236 ,  0.22984529,  0.4326722 ]])

Por otra parte, si tenemos dos vectores:

In [123]:
x, y

(array([ 4,  5,  8, -2,  3]), array([ 3,  1, -7, -9,  5]))

podemos calcular su producto interno (producto punto)

In [124]:
x.dot(y)

-6

In [125]:
(x * y).sum()

-6

In [135]:
x[:3], y[:3]

(array([4, 5, 8]), array([ 3,  1, -7]))

In [134]:
np.cross(x[:3], y[:3])

array([-43,  52, -11])

De la misma manera, podemos calcular la multiplicación de la matriz A por un vector

In [128]:
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

In [126]:
z = np.array([1, 0, 1])

In [127]:
A.dot(z)

array([2, 3, 3])

$$
A x = z
$$

In [129]:
np.linalg.inv(A).dot(z)

array([ 0.57142857, -0.57142857,  0.42857143])

In [130]:
np.linalg.solve(A, z)

array([ 0.57142857, -0.57142857,  0.42857143])

In [131]:
help(np.linalg.cross)

AttributeError: module 'numpy.linalg' has no attribute 'cross'

In [136]:
help(np.linalg.svd)

Help on function svd in module numpy.linalg:

svd(a, full_matrices=True, compute_uv=True, hermitian=False)
    Singular Value Decomposition.
    
    When `a` is a 2D array, it is factorized as ``u @ np.diag(s) @ vh
    = (u * s) @ vh``, where `u` and `vh` are 2D unitary arrays and `s` is a 1D
    array of `a`'s singular values. When `a` is higher-dimensional, SVD is
    applied in stacked mode as explained below.
    
    Parameters
    ----------
    a : (..., M, N) array_like
        A real or complex array with ``a.ndim >= 2``.
    full_matrices : bool, optional
        If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
        ``(..., N, N)``, respectively.  Otherwise, the shapes are
        ``(..., M, K)`` and ``(..., K, N)``, respectively, where
        ``K = min(M, N)``.
    compute_uv : bool, optional
        Whether or not to compute `u` and `vh` in addition to `s`.  True
        by default.
    hermitian : bool, optional
        If True, `a` is assumed to be

In [138]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
np.einsum('ii', a)

60

In [140]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

**Recomendado el siguiente [tutorial](https://www.numpy.org/devdocs/user/quickstart.html) para que profundicen más en todo lo que pueden hacer con NumPy**

<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#808080; background:#fff;">
Created with Jupyter by Esteban Jiménez Rodríguez.
</footer>