# Tarea 3: Clases 4 y 5

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="300px" height="300px" />

Cada clase que veamos tendrá una tarea asignada, la cual contendrá problemas varios que se pueden resolver con lo visto en clase, de manera que puedas practicar lo que acabas de aprender.

En esta ocasión, la tarea tendrá ejercicios relativos a la clases 4 y 5, de la librería NumPy y la librería Matplotlib.

Para resolver la tarea, por favor cambiar el nombre del archivo a "Tarea3_ApellidoNombre.ipynb", sin acentos ni letras ñ (ejemplo: en mi caso, el archivo se llamaría "Tarea3_JimenezEsteban.ipynb"). Luego de haber cambiado el nombre, resolver cada uno de los puntos en los espacios provistos.

Referencias:
- http://www.math.pitt.edu/~sussmanm/3040Summer14/exercisesII.pdf
- https://scipy-lectures.org/intro/numpy/exercises.html

**Todos los ejercicios se pueden realizar sin usar ciclos `for` ni `while`**
___

## 1. Cuadrado mágico

Un cuadrado mágico es una matriz cuadrada tal que las sumas de los elementos de cada una de sus filas, las sumas de los elementos de cada una de sus columnas y las sumas de los elementos de cada una de sus diagonales son iguales (hay dos diagonales: una desde el elemento superior izquierdo hasta el elemento inferior derecho, y otra desde el elemento superior derecho hasta el elemento inferior izquierdo).

Muestre que la matriz A dada por:

In [3]:
import numpy as np

In [4]:
A = np.array([[17, 24,  1,  8, 15],
              [23,  5,  7, 14, 16],
              [ 4,  6, 13, 20, 22],
              [10, 12, 19, 21,  3],
              [11, 18, 25,  2,  9]])

constituye un cuadrado mágico.

Ayuda: las funciones `np.sum()`, `np.diag()` y `np.fliplr()` pueden ser de mucha utilidad

In [5]:
def get_reverse_diagonal(my_array):
    #We have to invert A Array in order to get the reversed diagonal
    inverted_A = np.fliplr(A)
    return np.diag(inverted_A, k = 0)

In [6]:
r_0, r_1, r_2, r_3, r_4  = A[0], A[1], A[2], A[3], A[4]
r_0, r_1, r_2, r_3, r_4

(array([17, 24,  1,  8, 15]),
 array([23,  5,  7, 14, 16]),
 array([ 4,  6, 13, 20, 22]),
 array([10, 12, 19, 21,  3]),
 array([11, 18, 25,  2,  9]))

In [7]:
c_0, c_1, c_2, c_3, c_4  = A[:, 0], A[:, 1], A[:, 2], A[:, 3], A[:, 4]
c_0, c_1, c_2, c_3, c_4

(array([17, 23,  4, 10, 11]),
 array([24,  5,  6, 12, 18]),
 array([ 1,  7, 13, 19, 25]),
 array([ 8, 14, 20, 21,  2]),
 array([15, 16, 22,  3,  9]))

In [8]:
#ul to lr / ur to ll
ul_lr, ur_ll = np.diag(A), get_reverse_diagonal(A)
ul_lr, ur_ll

(array([17,  5, 13, 21,  9]), array([15, 14, 13, 12, 11]))

In [9]:
sum(ul_lr), sum(ur_ll), sum(r_0), sum(r_1), sum(r_2), sum(r_3), sum(r_4), sum(c_0), sum(c_1), sum(c_2), sum(c_3), sum(c_4) 

(65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65)

## 2. ¿Qué más podemos hacer con NumPy?

Este ejercicio es más que nada informativo, para ver qué más pueden hacer con la librería NumPy.

Considere el siguiente vector:

In [10]:
x = np.array([-1., 4., -9.])

1. La función coseno (`np.cos()`) se aplica sobre cada uno de los elementos del vector. Calcular el vector `y = np.cos(np.pi/4*x)`

In [12]:
y = np.cos(np.pi/4*x)
y

array([ 0.70710678, -1.        ,  0.70710678])

2. Puedes sumar vectores y multiplicarlos por escalares. Calcular el vector `z = x + 2*y`

In [14]:
z = x + 2*y
z

array([ 0.41421356,  2.        , -7.58578644])

3. También puedes calcular la norma de un vector. Investiga como y calcular la norma del vector x

Ayuda: buscar en las funciones del paquete de algebra lineal de NumPy

In [18]:
print(x)
np.linalg.norm(x)

[-1.  4. -9.]


9.899494936611665

4. Utilizando la función `np.vstack()` formar una matriz `M` tal que la primera fila corresponda al vector `x`, la segunda al vector `y` y la tercera al vector `z`.

In [24]:
M = np.vstack((x, y, z))
M

array([[-1.        ,  4.        , -9.        ],
       [ 0.70710678, -1.        ,  0.70710678],
       [ 0.41421356,  2.        , -7.58578644]])

5. Calcule la transpuesta de la matriz `M`, el determinante de la matriz `M`, y la multiplicación matricial de la matriz `M` por el vector `x`.

In [23]:
#Numpy transpose
M.transpose()

array([[-1.        ,  0.70710678,  0.41421356],
       [ 4.        , -1.        ,  2.        ],
       [-9.        ,  0.70710678, -7.58578644]])

In [28]:
#Linalg determinant
np.linalg.det(M)

0.0

In [38]:
print(np.dot(M, x))

[ 98.         -11.07106781  75.85786438]


## 3. Graficando funciones

Generar un gráfico de las funciones $f(x)=e^{-x/10}\sin(\pi x)$ y $g(x)=x e^{-x/3}$ sobre el intervalo $[0, 10]$. Incluya las etiquetas de los ejes y una leyenda con las etiquetas de cada función.

## 4. Analizando datos

Los datos en el archivo `populations.txt` describen las poblaciones de liebres, linces (y zanahorias) en el norte de Canadá durante 20 años.

Para poder analizar estos datos con NumPy es necesario importarlos. La siguiente celda importa los datos del archivo `populations.txt`, siempre y cuando el archivo y el notebook de jupyter estén en la misma ubicación:

In [2]:
data = np.loadtxt('populations.txt')

1. Obtener, usando la indización de NumPy, cuatro arreglos independientes llamados `años`, `liebres`, `linces` y `zanahorias`, correspondientes a los años, a la población de liebres, a la población de linces y a la cantidad de zanahorias, respectivamente.

2. Calcular e imprimir los valores priomedio y las desviaciones estándar de las poblaciones de cada especie.

3. ¿En qué año tuvo cada especie su población máxima?, y ¿cuál fue la población máxima de cada especie?

4. Graficar las poblaciones respecto al tiempo. Incluir en la gráfica los puntos de población máxima (resaltarlos con puntos grandes o de color, o con flechas y texto, o de alguna manera que se les ocurra). No olvidar etiquetar los ejes y poner una leyenda para etiquetar los diferentes objetos de la gráfica.

5. Graficar las distribuciones de las diferentes especies utilizando histogramas. Asegúrese de elegir parámetros adecuados de las gráficas.

6. Calcule el coeficiente de correlación de la población de linces y la población de liebres (ayuda: np.corrcoef). Por otra parte, mediante un gráfico de dispersión de puntos, grafique la población de linces vs. la población de liebres, ¿coincide la forma del gráfico con el coeficiente de correlación obtenido?

<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#808080; background:#fff;">
Created with Jupyter by Esteban Jiménez Rodríguez.
</footer>